const mongoose = require('mongoose');

const signUpTemplate = new mongoose.Schema({
    fullname: String,
    birthday: Date,
    gender: String,
    pronouns: String,
    nationality: String,
    ethnicity: String,
    onCampus: Boolean,
    college: String,
    room: String,
    street: String,
    zip: String,
    city: String,
    country: String,
    email: String,
    phone: String,
    university: String,
    degree: String,
    major: String,
    gradYear: String,
    exp: Boolean,
    prevHack: String,
    whyApply: String,
    drive: String,
    creativity: String,
    role: String,
    strength: String,
    weakness: String,
    built: String,
    achieve: String,
    partTeam: String,
    team: Boolean,
    teamMembers: String,
    diet: String,
    tshirt: String,
    needs: String,
    questions: String,
    linkedin: String,
    github: String,
    cvlink: String,
    terms: Boolean,
    mlh: Boolean,
    privacy: Boolean,
    date: {
        type: Date,
        default: Date.now,
    },
});

module.exports = mongoose.model('registrationtables', signUpTemplate);